### ISSUE TITLE
Kompatibilitätsprobleme zwischen DOS und UNIX Dateiformaten

### ISSUE THREAD

**Issue by lagru** [supergeorg/bv_v2_matlab#3]
Siehe 6c22b8b85962943abb2e11ef85ea937da82e2210.

Da solltest du informiert sein, wenn entsprechend gemergt wird. Sollten wir in Zukunft vielleicht nochmal die Editoren vernünftig einrichten.

**Comment by supergeorg** [comment]
Ok, schaue ich mir beim nächsten mal an.
